#!/bin/bash

echo "🚀 Yandex手动搜索工具"
echo "======================"
echo ""
echo "🎯 目标: 找到8张最相似的项链图片"
echo "⏰ 时间: 5分钟"
echo "💰 成本: 0元"
echo ""
echo "📋 操作步骤:"
echo ""
echo "1️⃣ 打开Yandex图片搜索"
echo "   https://yandex.com/images/"
echo ""
echo "2️⃣ 上传源图片"
echo "   - 点击 'Search by image' 按钮 (相机图标)"
echo "   - 点击 'Upload file' 按钮"
echo "   - 选择文件: /home/wang/桌面/测试结果/源图_项链.png"
echo ""
echo "3️⃣ 等待搜索结果 (3-5秒)"
echo ""
echo "4️⃣ 保存8张最相似的图片"
echo "   - 右键点击 → '图片另存为'"
echo "   - 保存到: $(pwd)/手动结果/"
echo "   - 命名: yandex_necklace_1.jpg 到 yandex_necklace_8.jpg"
echo ""
echo "🛠️ 工具命令:"
echo ""
echo "# 创建结果目录"
echo "mkdir -p 手动结果"
echo ""
echo "# 打开Yandex图片搜索"
echo "xdg-open 'https://yandex.com/images/'"
echo ""
echo "# 查看源图片"
echo "xdg-open '/home/wang/桌面/测试结果/源图_项链.png'"
echo ""
echo "# 验证结果"
echo "cd 手动结果 && ls -la *.jpg"
echo ""
echo "📊 选择标准:"
echo "1. ✅ 材质匹配: 白金/银色系优先"
echo "2. ✅ 款式匹配: 设计复杂度相似"
echo "3. ✅ 亮度匹配: 高亮度表面优先"
echo "4. ✅ 质量要求: 清晰、无水印、分辨率高"
echo ""
echo "💡 提示:"
echo "- 选择最相似的8张，不要凑数"
echo "- 保存原尺寸图片，不要缩略图"
echo "- 可以打开大图查看细节"
echo ""
echo "⏰ 时间预估:"
echo "- 打开网站: 10秒"
echo "- 上传图片: 10秒"
echo "- 等待结果: 5秒"
echo "- 保存8张图片: 2分钟"
echo "- 总计: <3分钟"
echo ""
echo "🚀 立即开始操作！完成后运行验证脚本:"
echo "./验证手动结果.sh"